# Generated by Django 4.0.2 on 2022-02-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование')),
                ('shortname', models.CharField(max_length=10, verbose_name='Наименование (краткое)')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Все специальности',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('regyear', models.PositiveIntegerField(verbose_name='Год регистрации')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Все группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('lastname', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.specialtygroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Все студенты',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Учебный предмет',
                'verbose_name_plural': 'Все учебные предметы',
            },
        ),
        migrations.CreateModel(
            name='StudSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(verbose_name='Дата начала сессии')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='Дата конца сессии')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Все сессии',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.studsession', verbose_name='Сессия')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Все оценки',
            },
        ),
    ]
