# Generated by Django 4.0.2 on 2022-02-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_studsession_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialtyGroup',
            new_name='Group',
        ),
    ]
