# Generated by Django 4.0.3 on 2022-04-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
